//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.01.09 at 02:32:19 PM GMT
//


package com.stackhawk.school;

import com.stackhawk.school.entity.Student;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Student" type="{http://localhost/vulnysoap}Student"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "student"
})
@XmlRootElement(name = "StudentSearchResponse")
public class StudentSearchResponse {

    @XmlElement(name = "Student", required = true)
    protected ArrayList<Student> students;

    /**
     * Gets the value of the student property.
     *
     * @return
     *     possible object is
     *     {@link Student }
     *
     */
    public List<Student> getStudents() {
        return students;
    }

    /**
     * Sets the value of the student property.
     *
     * @param value
     *     allowed object is
     *     {@link Student }
     *
     */
    public void addStudent(Student value) {
        this.students.add(value);
    }

    public void setStudents(List<Student> value) {
        this.students.clear();
        this.students.addAll(value);
    }

}
